### ISSUE TITLE
Можно настроить на работу с клипбордом?

### ISSUE THREAD

**Issue by vandesign** [voldmar/alfred-typograf#1]
Спасибо! Удобно.

Было бы удобнее если бы скрипт работал исключительно с клипбордом и не пытался вставлять исправленный текст на место.
Работаю с InDesign – текст просто удаляется по нажатию горячих клавиш.
Хороший вариант – скопировал текст, нажал горячие клавиши – текст почистился типографом – вставил чистый куда надо.

еще раз спасибо.

**Comment by voldmar** [comment]
Да, можно: в настройках горячих клавиш выбрать «OS X Clipboard contents», а в настройках последнего шага убрать галочку «Automatically paste to front most app»

**Comment by voldmar** [comment]
Обновил документацию

**Comment by vandesign** [comment]
Огромное спасибо! Всё работает.
