### ISSUE TITLE
Перестал работать в Альфреде

### ISSUE THREAD

**Issue by Khilkov** [voldmar/alfred-typograf#2]
Долгие годы пользуюсь Типографом и вот второй день он не работает. Это только у меня проблема?

**Comment by nikitagukov** [comment]
У меня тоже не работает: https://disk.yandex.ru/i/98c9gD8DWl0Auw

**Comment by kutovova** [comment]
Тоже не работает

**Comment by voldmar** [comment]
О, дякую, забув погасити проєкт
